class PortEntry {
  final int port;
  final String service;
  final String protocol;
  final String description;

  const PortEntry({
    required this.port,
    required this.service,
    required this.protocol,
    required this.description,
  });
}

const List<PortEntry> commonPorts = [
  PortEntry(port: 20, service: 'FTP Data', protocol: 'TCP', description: 'File Transfer Protocol — data transfer'),
  PortEntry(port: 21, service: 'FTP Control', protocol: 'TCP', description: 'File Transfer Protocol — command channel'),
  PortEntry(port: 22, service: 'SSH', protocol: 'TCP', description: 'Secure Shell — remote login and tunneling'),
  PortEntry(port: 23, service: 'Telnet', protocol: 'TCP', description: 'Unencrypted text communications'),
  PortEntry(port: 25, service: 'SMTP', protocol: 'TCP', description: 'Simple Mail Transfer Protocol — email sending'),
  PortEntry(port: 53, service: 'DNS', protocol: 'TCP/UDP', description: 'Domain Name System — hostname resolution'),
  PortEntry(port: 67, service: 'DHCP Server', protocol: 'UDP', description: 'Dynamic Host Configuration Protocol — IP assignment'),
  PortEntry(port: 68, service: 'DHCP Client', protocol: 'UDP', description: 'DHCP client port'),
  PortEntry(port: 69, service: 'TFTP', protocol: 'UDP', description: 'Trivial File Transfer Protocol'),
  PortEntry(port: 80, service: 'HTTP', protocol: 'TCP', description: 'Hypertext Transfer Protocol — standard web'),
  PortEntry(port: 88, service: 'Kerberos', protocol: 'TCP/UDP', description: 'Kerberos authentication protocol'),
  PortEntry(port: 110, service: 'POP3', protocol: 'TCP', description: 'Post Office Protocol v3 — email retrieval'),
  PortEntry(port: 119, service: 'NNTP', protocol: 'TCP', description: 'Network News Transfer Protocol'),
  PortEntry(port: 123, service: 'NTP', protocol: 'UDP', description: 'Network Time Protocol — time sync'),
  PortEntry(port: 135, service: 'RPC', protocol: 'TCP', description: 'Microsoft RPC Endpoint Mapper'),
  PortEntry(port: 139, service: 'NetBIOS', protocol: 'TCP', description: 'NetBIOS Session Service'),
  PortEntry(port: 143, service: 'IMAP', protocol: 'TCP', description: 'Internet Message Access Protocol — email retrieval'),
  PortEntry(port: 161, service: 'SNMP', protocol: 'UDP', description: 'Simple Network Management Protocol'),
  PortEntry(port: 162, service: 'SNMP Trap', protocol: 'UDP', description: 'SNMP trap notifications'),
  PortEntry(port: 179, service: 'BGP', protocol: 'TCP', description: 'Border Gateway Protocol — internet routing'),
  PortEntry(port: 194, service: 'IRC', protocol: 'TCP', description: 'Internet Relay Chat'),
  PortEntry(port: 389, service: 'LDAP', protocol: 'TCP', description: 'Lightweight Directory Access Protocol'),
  PortEntry(port: 443, service: 'HTTPS', protocol: 'TCP', description: 'HTTP Secure — encrypted web traffic'),
  PortEntry(port: 445, service: 'SMB', protocol: 'TCP', description: 'Server Message Block — Windows file sharing'),
  PortEntry(port: 465, service: 'SMTPS', protocol: 'TCP', description: 'SMTP over SSL — secure email sending'),
  PortEntry(port: 500, service: 'IKE', protocol: 'UDP', description: 'Internet Key Exchange — IPSec VPN'),
  PortEntry(port: 514, service: 'Syslog', protocol: 'UDP', description: 'System logging daemon'),
  PortEntry(port: 515, service: 'LPD', protocol: 'TCP', description: 'Line Printer Daemon — print server'),
  PortEntry(port: 587, service: 'SMTP (Submission)', protocol: 'TCP', description: 'Email submission port with STARTTLS'),
  PortEntry(port: 631, service: 'IPP', protocol: 'TCP', description: 'Internet Printing Protocol / CUPS'),
  PortEntry(port: 636, service: 'LDAPS', protocol: 'TCP', description: 'LDAP over SSL'),
  PortEntry(port: 993, service: 'IMAPS', protocol: 'TCP', description: 'IMAP over SSL — secure email retrieval'),
  PortEntry(port: 995, service: 'POP3S', protocol: 'TCP', description: 'POP3 over SSL'),
  PortEntry(port: 1080, service: 'SOCKS Proxy', protocol: 'TCP', description: 'SOCKS proxy protocol'),
  PortEntry(port: 1194, service: 'OpenVPN', protocol: 'TCP/UDP', description: 'OpenVPN tunnel'),
  PortEntry(port: 1433, service: 'MSSQL', protocol: 'TCP', description: 'Microsoft SQL Server'),
  PortEntry(port: 1521, service: 'Oracle DB', protocol: 'TCP', description: 'Oracle Database listener'),
  PortEntry(port: 1723, service: 'PPTP', protocol: 'TCP', description: 'Point-to-Point Tunneling Protocol (VPN)'),
  PortEntry(port: 2049, service: 'NFS', protocol: 'TCP/UDP', description: 'Network File System'),
  PortEntry(port: 2181, service: 'ZooKeeper', protocol: 'TCP', description: 'Apache ZooKeeper client port'),
  PortEntry(port: 2375, service: 'Docker API', protocol: 'TCP', description: 'Docker Engine REST API (unencrypted)'),
  PortEntry(port: 2376, service: 'Docker TLS', protocol: 'TCP', description: 'Docker Engine REST API (TLS)'),
  PortEntry(port: 2377, service: 'Docker Swarm', protocol: 'TCP', description: 'Docker Swarm management'),
  PortEntry(port: 3000, service: 'Dev Server', protocol: 'TCP', description: 'Common development server port (React, Node, etc.)'),
  PortEntry(port: 3306, service: 'MySQL', protocol: 'TCP', description: 'MySQL / MariaDB database server'),
  PortEntry(port: 3389, service: 'RDP', protocol: 'TCP', description: 'Remote Desktop Protocol — Windows remote access'),
  PortEntry(port: 4000, service: 'Dev Server', protocol: 'TCP', description: 'Common development server port'),
  PortEntry(port: 4369, service: 'EPMD', protocol: 'TCP', description: 'Erlang Port Mapper — RabbitMQ'),
  PortEntry(port: 5000, service: 'Dev Server', protocol: 'TCP', description: 'Flask / Python development server'),
  PortEntry(port: 5432, service: 'PostgreSQL', protocol: 'TCP', description: 'PostgreSQL database server'),
  PortEntry(port: 5601, service: 'Kibana', protocol: 'TCP', description: 'Elasticsearch Kibana dashboard'),
  PortEntry(port: 5672, service: 'AMQP', protocol: 'TCP', description: 'RabbitMQ / AMQP message broker'),
  PortEntry(port: 5900, service: 'VNC', protocol: 'TCP', description: 'Virtual Network Computing — remote desktop'),
  PortEntry(port: 6379, service: 'Redis', protocol: 'TCP', description: 'Redis in-memory data store'),
  PortEntry(port: 6443, service: 'Kubernetes API', protocol: 'TCP', description: 'Kubernetes API server'),
  PortEntry(port: 7000, service: 'Cassandra', protocol: 'TCP', description: 'Apache Cassandra inter-node communication'),
  PortEntry(port: 7001, service: 'Cassandra TLS', protocol: 'TCP', description: 'Cassandra TLS inter-node'),
  PortEntry(port: 7474, service: 'Neo4j', protocol: 'TCP', description: 'Neo4j graph database HTTP'),
  PortEntry(port: 8000, service: 'Alt HTTP', protocol: 'TCP', description: 'Alternative HTTP / Django dev server'),
  PortEntry(port: 8008, service: 'Alt HTTP', protocol: 'TCP', description: 'Alternative HTTP port'),
  PortEntry(port: 8080, service: 'HTTP Proxy', protocol: 'TCP', description: 'Alternative HTTP / Tomcat / common proxy'),
  PortEntry(port: 8081, service: 'HTTP Alt', protocol: 'TCP', description: 'Secondary HTTP port'),
  PortEntry(port: 8086, service: 'InfluxDB', protocol: 'TCP', description: 'InfluxDB time-series HTTP API'),
  PortEntry(port: 8088, service: 'Superset', protocol: 'TCP', description: 'Apache Superset web interface'),
  PortEntry(port: 8443, service: 'HTTPS Alt', protocol: 'TCP', description: 'Alternative HTTPS port'),
  PortEntry(port: 8888, service: 'Jupyter', protocol: 'TCP', description: 'Jupyter Notebook server'),
  PortEntry(port: 9000, service: 'SonarQube', protocol: 'TCP', description: 'SonarQube / PHP-FPM / MinIO'),
  PortEntry(port: 9090, service: 'Prometheus', protocol: 'TCP', description: 'Prometheus metrics server'),
  PortEntry(port: 9092, service: 'Kafka', protocol: 'TCP', description: 'Apache Kafka broker'),
  PortEntry(port: 9200, service: 'Elasticsearch', protocol: 'TCP', description: 'Elasticsearch REST API'),
  PortEntry(port: 9300, service: 'Elasticsearch', protocol: 'TCP', description: 'Elasticsearch inter-node communication'),
  PortEntry(port: 9418, service: 'Git', protocol: 'TCP', description: 'Git protocol'),
  PortEntry(port: 27017, service: 'MongoDB', protocol: 'TCP', description: 'MongoDB database server'),
  PortEntry(port: 27018, service: 'MongoDB Shard', protocol: 'TCP', description: 'MongoDB shard server'),
  PortEntry(port: 27019, service: 'MongoDB Config', protocol: 'TCP', description: 'MongoDB config server'),
];
